meta_product_name: "HobbyBuddy"
meta_title: "HobbyBuddy - Connect with people who have same interests."
meta_description: "Find new friends and improve your skills together"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
